repos:
  - hooks:
      - id: commitizen
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.32.2
  - hooks:
      - id: gradle-check
        args: [ "-w" ]
    repo: https://github.com/jguttman94/pre-commit-gradle
    rev: v0.2.1